### ISSUE TITLE
sub_add raises an error

### ISSUE THREAD

**Issue by chama-chomo** [jaseg/python-mpv#119]
Hey, I'd like to add subtitles file for the video, but it gets refused when I feed `sub_add` method with a name of the file in the current directory. Is this s proper way of adding subtitles, please? Thanks

```
2020-07-10 11:50:43,004 [INFO] Subtitles file: 3977366.srt
Traceback (most recent call last):
  File "./wsosac.py", line 216, in <module>
    main()
  File "./wsosac.py", line 203, in main
    play_video(link, sub_name)
  File "./wsosac.py", line 81, in play_video
    player.sub_add(sub_name)  #  not working
  File "/home/cqs/.local/share/virtualenvs/wsosac-VwlSFq53/lib/python3.8/site-packages/mpv.py", line 960, in sub_add
    self.command('sub_add', filename.encode(fs_enc))
  File "/home/cqs/.local/share/virtualenvs/wsosac-VwlSFq53/lib/python3.8/site-packages/mpv.py", line 852, in command
    _mpv_command(self.handle, (c_char_p*len(args))(*args))
  File "/home/cqs/.local/share/virtualenvs/wsosac-VwlSFq53/lib/python3.8/site-packages/mpv.py", line 129, in raise_for_ec
    raise ex(ec, *args)
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7fbbd8921340>, <mpv.c_char_p_Array_3 object at 0x7fbbd8955b40>))```

**Comment by McSinyx** [comment]
Hello there, could you please the script, the video (I assume) and the subtitle file so that it's easier to reproduce and investigate?

**Comment by chama-chomo** [comment]
In fact it doesn't work with any subs, my project is quite big, but I'm using this function to play the video, I feed it with video URL and downloaded subtitles (in the current directory)

As a W/A I'm setting up 'sub-file-paths' to the current dir, then subs are found by mpv. (commented for now)

```
def play_video(video_path, sub_name):
    """Use mpv lib to play the stuff."""
    player = mpv.MPV(log_handler=print, input_default_bindings=True, input_vo_keyboard=True)
    player.fullscreen = True
    # player['sub-file-paths'] = os.getcwd()
    # player['sub-auto'] = 'all'
    LOGGER.info('Subtitles file: %s', sub_link)
    player.sub_add(sub_name)  #  not working
    player.play(video_path)
    player.wait_for_playback()
    player.terminate()

    del player
```
As an example:
URL of the subtitles:  
```
https://www.opensubtitles.com/download/E3A4E20327363AE8C62A1E03181846D15149018242D9BC138216C9959826B99FA79AB5A3080F6B2450B40EB77E05E854327C19E66D6D45223D03868C56E52DFCBC8D096AD9BECCE65186CED98D4E6C71DF64E01697621E516D43B9D224DF8FF85014D6B11D431321709D11B5D361A3D0EA72E20C4BD839B50AFCD261D6CDB6659133B8EAE768E9994466F0547A42D4A8B6F257946277ED9023240996AD8482FD5DF88F958693F6A3F8F82B22E39E7875D8669F2B4521DB938FBA112631F631669919510CB133E248/subfile/3977366.srt
```
URL of the video:
```
https://vip.6.dl.webshare.cz/8103/ti2c53d6oK/524288000/eJw1jstqwzAQRX+lzKK0IGSNXmMJQj4g4G4SuvFGtiVqauIi2wmk9N+jBLq8h_v6hQAetOWoDFeKI0lgsIJH47Sx0gnB4FIkgw08OUFkGSxP8AN+zVtkcC4Vx7nL2_fLmxSifufhMpaaofDedZZE0EIOOJA1lJTtXUQ0KahYE5mEqY7pYS+z522aGOQSvMZu+Qo58v7WVmmcYluto+yNGux8aKt9zHnOu1NzaD4+m9d597id_x8tN_COtEVE0n93FWc+Tg../ce14ed3f96d585ac9aab62890522eab1162a4a66/Tobruk-2008.avi
```

```
→ file 3977366.srt                                                                                                                                                                              [a04942c]
3977366.srt: UTF-8 Unicode text
```


btw, according to man pages of MPV I should be even able to play subtitles as a stream, is that correct please?

**Comment by McSinyx** [comment]
> according to man pages of MPV I should be even able to play subtitles as a stream, is that correct

I'm not sure, but for me
```console
$ mpv 3977366.srt 
     Subs  --sid=1 (subrip)
No video or audio streams selected.


Exiting... (Errors when loading file)
```
so I guess it's a no (I haven't found the part mentioning it in the man page though).  Because of this, you need to have the video playing before adding the subtitles.  This works for me:
```python
from operator import not_

player.play(video)
player.wait_for_property('idle', not_)
player.sub_add(sub)
```

**Comment by chama-chomo** [comment]
Unfortunately it doesn't work for me, can you please advice me what am I doing wrong? here is the code I'm running:

```
#!/usr/bin/env python3
import mpv
from operator import not_

video = 'https://vip.6.dl.webshare.cz/8103/ti2c53d6oK/524288000/eJw1jstqwzAQRX+lzKK0IGSNXmMJQj4g4G4SuvFGtiVqauIi2wmk9N+jBLq8h_v6hQAetOWoDFeKI0lgsIJH47Sx0gnB4FIkgw08OUFkGSxP8AN+zVtkcC4Vx7nL2_fLmxSifufhMpaaofDedZZE0EIOOJA1lJTtXUQ0KahYE5mEqY7pYS+z522aGOQSvMZu+Qo58v7WVmmcYluto+yNGux8aKt9zHnOu1NzaD4+m9d597id_x8tN_COtEVE0n93FWc+Tg../ce14ed3f96d585ac9aab62890522eab1162a4a66/Tobruk-2008.avi'

subs = './3977366.srt'

player = mpv.MPV(log_handler=print, input_default_bindings=True, input_vo_keyboard=True)
player.play(video1)
# player.wait_for_playback()
player.wait_for_property('idle', not_)
player.sub_add(subs)
player.terminate()

del player
```
No subs found when I press 'J' or 'V' while running a video.

This is a man page I was reading about the sub streams.
![image](https://user-images.githubusercontent.com/34240896/87195519-f87fed00-c2f9-11ea-951a-c017fc70d89c.png)

**Comment by McSinyx** [comment]
My mistake, I used the video and sub in the same dir with compatible names so the subs are automatically recognized.  @jaseg, do you have any idea why this happens?

**Comment by jaseg** [comment]
The following works for me, with `idle` replaced by `core-idle`:

```python3
#!/usr/bin/env python3
import mpv
from operator import not_

video = 'https://vip.6.dl.webshare.cz/8103/ti2c53d6oK/524288000/eJw1jstqwzAQRX+lzKK0IGSNXmMJQj4g4G4SuvFGtiVqauIi2wmk9N+jBLq8h_v6hQAetOWoDFeKI0lgsIJH47Sx0gnB4FIkgw08OUFkGSxP8AN+zVtkcC4Vx7nL2_fLmxSifufhMpaaofDedZZE0EIOOJA1lJTtXUQ0KahYE5mEqY7pYS+z522aGOQSvMZu+Qo58v7WVmmcYluto+yNGux8aKt9zHnOu1NzaD4+m9d597id_x8tN_COtEVE0n93FWc+Tg../ce14ed3f96d585ac9aab62890522eab1162a4a66/Tobruk-2008.avi'

subs = './test.srt'

player = mpv.MPV(log_handler=print, input_default_bindings=True, input_vo_keyboard=True, loglevel='debug')
player.play(video)
player.wait_for_property('core-idle', not_)
print("################################## SUB ADD ##################################")
print("################################## SUB ADD ##################################")
print("################################## SUB ADD ##################################")
print("################################## SUB ADD ##################################")
print("################################## SUB ADD ##################################")
player.sub_add(subs)

player.wait_for_playback()
player.terminate()

del player
```
`idle` indicates the player is idling, i.e. not playing anything. `core-idle` means the playback core is available for commands.

**Comment by chama-chomo** [comment]
Thanks! it works perfectly. If you agree I'll submit a commit to update README on how to add subtitles. Someone else might find it useful too.

**Comment by jaseg** [comment]
Yes please! Thank you!
