### ISSUE TITLE
mpv.MPV(video=False) works but video=True does not

### ISSUE THREAD

**Issue by jakeogh** [jaseg/python-mpv#120]
Using git-latest:

```
$ cat test.py 
#!/usr/bin/env python3

import sys
import mpv

try:
    if sys.argv[1] == "--no-video":
        video = False
except IndexError:
    video = True

player = mpv.MPV(ytdl=True, video=video)
player.play('https://youtu.be/DOmdB7D-pUU')
player.wait_for_playback()


$ /usr/bin/mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.66.101
   libavformat     58.35.104
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: N-96486-g1ab302da6e


$ ./test.py --no-video
 # (audio plays)

$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    player = mpv.MPV(ytdl=True, video=video)
  File "/usr/lib/python3.7/site-packages/mpv.py", line 769, in __init__
    _mpv_set_option_string(self.handle, k.replace('_', '-').encode('utf-8'), istr(v).encode('utf-8'))
  File "/usr/lib/python3.7/site-packages/mpv.py", line 129, in raise_for_ec
    raise ex(ec, *args)
ValueError: ('Invalid value for mpv option', -7, (<MpvHandle object at 0x7f73f553e4d0>, b'video', b'yes'))
```

**Comment by jaseg** [comment]
According to the mpv souces, the "video" option is an alias for the "vid" option. This option is of type OPT_TRACKCHOICE and can take values "no", "auto" or an integer video track ID. MPV(video=1) or MPV(video=0) should work if you want to select the first video track (I don't know whether vids are 0-indexed or 1-indexed).

https://github.com/mpv-player/mpv/blob/master/options/options.c#L480
https://github.com/mpv-player/mpv/blob/master/options/m_option.h#L644

**Comment by jaseg** [comment]
actually MPV(vid='auto') should be the default behavior

**Comment by jakeogh** [comment]
Hey thanks for the instant reply! I really appreciate it, and the links to the options source; I will consult those next time for sure.

Great library. 

For completeness, here is the fixed test.py, which is just binary video/novideo:

```
$ cat ./test.py 
#!/usr/bin/env python3

import sys
import mpv

try:
    if sys.argv[1] == "--no-video":
        video = False
except IndexError:
    video = 'auto'

player = mpv.MPV(ytdl=True, video=video)
player.play('https://youtu.be/DOmdB7D-pUU')
player.wait_for_playback()
```
