### ISSUE TITLE
problem with mpv module after i re install my os 

### ISSUE THREAD

**Issue by musicfunfan** [jaseg/python-mpv#168]
hello i run arch linux , and i have to do a format and re install of my os ... :( 

Now i try to run the example you have for python mpv 
this is the code 
`import mpv
player = mpv.MPV(ytdl=True)
player.play('https://youtu.be/DOmdB7D-pUU')
player.wait_for_playback()`

and this is the error massage i do something wrong ??
before the format this was working fine.

`Exception in callback MPV.__init__.<locals>.mpv_event_extractor() at /home/musicfan/.local/lib/python3.9/site-packages/mpv.py:276
handle: <Handle MPV.__init__.<locals>.mpv_event_extractor() at /home/musicfan/.local/lib/python3.9/site-packages/mpv.py:276>
Traceback (most recent call last):
  File "/home/musicfan/.local/lib/python3.9/site-packages/mpv.py", line 254, in _event_generator
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/musicfan/.local/lib/python3.9/site-packages/mpv.py", line 278, in mpv_event_extractor
    for event in _event_generator(self.handle):
RuntimeError: generator raised StopIteration
Exception in callback MPV.__init__.<locals>.mpv_event_extractor() at /home/musicfan/.local/lib/python3.9/site-packages/mpv.py:276
handle: <Handle MPV.__init__.<locals>.mpv_event_extractor() at /home/musicfan/.local/lib/python3.9/site-packages/mpv.py:276>
Traceback (most recent call last):
  File "/home/musicfan/.local/lib/python3.9/site-packages/mpv.py", line 254, in _event_generator
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/musicfan/.local/lib/python3.9/site-packages/mpv.py", line 278, in mpv_event_extractor
    for event in _event_generator(self.handle):
RuntimeError: generator raised StopIteration`

**Comment by musicfunfan** [comment]
btw on windows works just fine ... So the problem is in arch only

**Comment by musicfunfan** [comment]
ok i fixed i just have to install via package manager (os) and from the pip ,
Also i install this https://aur.archlinux.org/packages/mpv-full-build-git/ package for libmpv for my o.
Now is working....
