### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mikwee** [jaseg/python-mpv#219]
Got this error:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "d:\mlp-mpv\main.py", line 48, in playVideo
    player.play(link)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\mpv.py", line 1806, in play
    self.loadfile(filename)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\mpv.py", line 1291, in loadfile
    self.command('loadfile', filename.encode(fs_enc), mode, MPV._encode_options(options))
AttributeError: 'NoneType' object has no attribute 'encode'
```
I think this is related to how the package is written, but it could be related to how I installed the package. I heard it's hard on WIndows (I did install `mpv-1.dll`).

**Comment by mikwee** [comment]
For some reason, it detects the string variable I gave `play` as a `NoneType`, and I don't get why!

**Comment by dfaker** [comment]
`link` must be `None` almost nothing is going on between the call to play and calling the encode method on filename.

**Comment by mikwee** [comment]
I'll check the code when I come home.

**Comment by jaseg** [comment]
I agree that ```link``` must be None here. If it's indeed an issue in python-mpv, feel free to re-open this issue.
