### ISSUE TITLE
Flaky test `tests.test_mpv.RegressionTests.test_wait_for_property_concurrency` in Python3.12

### ISSUE THREAD

**Issue by baldurmen** [jaseg/python-mpv#286]
Hi,

It seems the `tests.test_mpv.RegressionTests.test_wait_for_property_concurrency` is flaky with Python3.12, using ` libmpv 0.38.0`.

I have to run the testsuite a couple of times to trigger the issue, but once it a while, it'll fail with:

```
======================================================================
ERROR: test_wait_for_property_concurrency (tests.test_mpv.RegressionTests.test_wait_for_property_concurrency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_python-mpv/build/tests/test_mpv.py", line 928, in test_wait_for_property_concurrency
    player.seek(0, reference='absolute', precision='exact')
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_python-mpv/build/mpv.py", line 1244, in seek
    self.command('seek', amount, reference, precision)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_python-mpv/build/mpv.py", line 1237, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_python-mpv/build/mpv.py", line 142, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7f75f918bdd0>, <mpv.LP_MpvNode object at 0x7f75f934b550>, <mpv.LP_MpvNode object at 0x7f75f9348250>))
```

A complete build log can be found here: https://people.debian.org/~sanvila/build-logs/202407/python-mpv_1.0.7-1_amd64-20240723T142304.770Z

**Comment by jaseg** [comment]
Thank you for the report! I'm able to reproduce this.

The issue happens when for whatever reason one of the two mpv instance that are racing in this test takes so long to start playing the file that the other instance has already finished playing. I've solved the issue on the main branch by just making the mpv instances loop the file. In 100 test runs I haven't seen another crash, so I assume this is fixed.

I'll probably push a new release including this fix later today.

**Comment by polyzen** [comment]
Getting this failure still with 1.0.8.

**Comment by baldurmen** [comment]
It seems that's indeed the case. Here's a build failure on the Debian build infrastructure with 1.0.8:

https://buildd.debian.org/status/fetch.php?pkg=python-mpv&arch=all&ver=1.0.8-1&stamp=1756870795&file=log
