### ISSUE TITLE
Fails with latest libmpv: TypeError: MPV._handle_key_binding_message() takes from 3 to 5 positional arguments but 7 were given

### ISSUE THREAD

**Issue by eric321** [jaseg/python-mpv#290]
I'm doing `player.wait_for_playback()` and expecting it to return or raise a ShutdownError.

Instead I get a `TypeError`:
```
Traceback (most recent call last):                         
  File "/tmp/mp", line 613, in <module>
    player.wait_for_playback()
  File "/disk1/clone/python-mpv/mpv.py", line 1010, in wait_for_playback
    self.wait_for_event('end_file', timeout=timeout, catch_errors=catch_errors)
  File "/disk1/clone/python-mpv/mpv.py", line 1101, in wait_for_event
    with self.prepare_and_wait_for_event(*event_types, cond=cond, timeout=timeout, catch_errors=catch_errors) as result:
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/disk1/clone/python-mpv/mpv.py", line 1146, in prepare_and_wait_for_event
    result.result(timeout)
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/disk1/clone/python-mpv/mpv.py", line 922, in _enqueue_exceptions
    yield
  File "/disk1/clone/python-mpv/mpv.py", line 964, in _loop
    self._message_handlers[target](*args)
TypeError: MPV._handle_key_binding_message() takes from 3 to 5 positional arguments but 7 were given
```

There were two recent commits in mpv that each added an argument:

* https://github.com/mpv-player/mpv/commit/34571e78822565cc0657b69217cb1eacd7c42b4a
* https://github.com/mpv-player/mpv/commit/0874f81b31a642a1381de16f272c4987077a9cff

This fixes it for me:
```
--- a/mpv.py
+++ b/mpv.py
@@ -1785,7 +1785,7 @@ class MPV(object):
             raise TypeError('register_key_binding expects either an str with an mpv command or a python callable.')
         self.command('enable-section', binding_name, 'allow-hide-cursor+allow-vo-dragging')
 
-    def _handle_key_binding_message(self, binding_name, key_state, key_name=None, key_char=None):
+    def _handle_key_binding_message(self, binding_name, key_state, key_name=None, key_char=None, *_):
         binding_name = binding_name.decode('utf-8')
         key_state = key_state.decode('utf-8')
         key_name = key_name.decode('utf-8') if key_name is not None else None
```

**Comment by jaseg** [comment]
@eric321 Thank you for the report. I've fixed this issue on the main branch, and the fix will be included in the next major release (since it changes the API).

**Comment by jaseg** [comment]
@ACBAD Please feel free to open a new issue if you can't solve this yourself. Make sure you pause the player in your keybind function using something like `mpv.pause = not mpv.pause`, since by default the standard key bindings (like pasuing/resuming playback when space is pressed) are not loaded when using mpv through libmpv.
