### ISSUE TITLE
AttributeError when running first "Advanced Usage" example

### ISSUE THREAD

**Issue by seanpianka** [jaseg/python-mpv#49]
```python
import mpv

def my_log(loglevel, component, message):
    print('[{}] {}: {}'.format(loglevel, component, message))

player = mpv.MPV(log_handler=my_log, ytdl=True, input_default_bindings=True, input_vo_keyboard=True)

# Property access, these can be changed at runtime
@player.property_observer('time-pos')
def time_observer(_name, value):
    # Here, _value is either None if nothing is playing or a float containing
    # fractional seconds since the beginning of the file.
    print('Now playing at {:.2f}s'.format(value))

player.fullscreen = True
player.loop = 'inf'
# Option access, in general these require the core to reinitialize
player['vo'] = 'opengl'

@player.on_key_press('q')
def my_q_binding():
    print('THERE IS NO ESCAPE')
...
```

```
[warn] cplayer: Warning: property 'loop' was replaced with 'loop-playlist' and might be removed in the future.                                                 
Traceback (most recent call last):     
  File "test2.py", line 20, in <module>                                        
    @player.on_key_press('q')          
  File "/home/sean/Development/.virtualenvs/music/lib/python3.6/site-packages/mpv.py", line 1028, in __getattr__                                               
    return self._get_property(_py_to_mpv(name), lazy_decoder)                  
  File "/home/sean/Development/.virtualenvs/music/lib/python3.6/site-packages/mpv.py", line 1011, in _get_property                                             
    cval = _mpv_get_property(self.handle, name.encode('utf-8'), fmt, outptr)   
  File "/home/sean/Development/.virtualenvs/music/lib/python3.6/site-packages/mpv.py", line 104, in raise_for_ec                                               
    raise ex(ec, *args)                
AttributeError: ('mpv property does not exist', -8, (<MpvHandle object at 0x7f963bde5620>, b'on-key-press', 6, <cparam 'P' (0x7f963bdf6808)>)) 
```
Latest commits, and:
```bash
$ python --version
Python 3.6.2
$ uname -a
Linux Caldera 4.12.8-1-ARCH #1 SMP PREEMPT Thu Aug 17 08:37:20 CEST 2017 x86_64 GNU/Linux
```

**Comment by jaseg** [comment]
The ```@on_key_press``` decorator demonstrated in that example was on master already but not yet published on pypi. Try again with version 0.3.4 from pypi which now includes that feature.

**Comment by jaseg** [comment]
I'll close this issue for now. If you have any further questions feel free to re-open it.
